#+title: Crit Comp
The =crit-comp= compares two solutions, it stands for criteria comparison. In optimizaition and simulation this is used to crawl solutions and find automatically the best according to that criteria.

For instance, the best solution could be the one with the lowest end time (often called makespan), or the one with the lower cost, with the higher occupation rate of a critical machine, ... 
* Why another criteria library?
The main reasons are:
- [[file:design_decisions.org][Decision 1]] makes the optimization chain flexible, it implies being able to switch easily from one criteria to another with a parameter map,
- Most comparisons are standard and their implementation should be available off the shelf and be battle tested.
* Quickstart
Use =crit-comp-fn= to create the function to compare two solutions. This function - called =crit-fn= compares the first parameter to the second one and returns =:better=, =:worst= or =:equal=.
#+begin_src clojure
(require '[auto-opti.crit-comp :as opti-crit]
         '[auto-opti :as-alias opti])

(def crit-fn
  (-> #::opti{:crit-comp-name :smaller}
      opti-crit/crit-comp-fn))

[(crit-fn 12 13)
 (crit-fn 13 12)
 (crit-fn 13 13)]
;; ==> [:better :worst :equal]
#+end_src

#+RESULTS:
: [:better :worst :equal]

* Usage
Describe the =crit-comp= in a parameter map which contains at least the name of the comparison to use. Choose among the criteria below or create your own. Note there may be additional parameters depending required by this comparison.

All comparisons return a value among ==:better=, =:worst= or =:equal=, some may include other values like =nc=.
* Numeric comparisons
The comparisons below concern numeric values, i.e. when the criteria to compare is numerical.
** smaller
For =smaller= comparison, the best solutions are the smaller ones:
#+begin_src clojure
(require '[auto-opti.crit-comp :as opti-crit]
         '[auto-opti :as-alias opti])

[(opti-crit/direct-eval #::opti{:crit-comp-name :smaller} 12 20)
 (opti-crit/direct-eval #::opti{:crit-comp-name :smaller} 12 12)
 (opti-crit/direct-eval #::opti{:crit-comp-name :smaller} 20 12)]
;; ==> [:better :equal :worst]
#+end_src

#+RESULTS:
: [:better :equal :worst]

** bigger
For =bigger= comparison, the best solutions are the bigger ones:
#+begin_src clojure
(require '[auto-opti.crit-comp :as opti-crit]
          '[auto-opti :as-alias opti])

[(opti-crit/direct-eval #::opti{:crit-comp-name :bigger} 12 20)
 (opti-crit/direct-eval #::opti{:crit-comp-name :bigger} 12 12)
 (opti-crit/direct-eval #::opti{:crit-comp-name :bigger} 20 12)]
;; ==> [:worst :equal :better]
#+end_src

#+RESULTS:
: [:worst :equal :better]

* Map criteria
The comparisons below concern map criteria, i.e. when the criteria to compare is a map, potentially containing multiple data.

A map criteria is useful for:
- storing other information in the criteria, useful for explanation, debugging, ...
- enabling multi-criteria, that all are necessary to compare the solutions ...
** hierarchise
Use =:hierarchise= when multiple values make the criteria but their relative importance is totally ordered.

Let's consider two criteria:
#+begin_src clojure
(def crit1 {:a 13 :b 2 :c 100})
(def crit2 {:a 13 :b 2 :c 99})
#+end_src
A hierarchised comparison of that criteria could be:
- First compare =crit1= and =crit2= on their =:a= value. =crit1= is better if value is smaller.
- If there is a tie, compare =crit1= and =crit2= on their =:b= value. =crit1= is better if value is smaller.
- ...

If all values are equal, the two solutions are equal and comparison returns =:equal=.

This comparison is implemented with =:hierarchise=, and criteria order is specified with =:order= parameter:
#+begin_src clojure
(require '[auto-opti.crit-comp :as opti-crit]
          '[auto-opti :as-alias opti])

(defn hierarchise-test [crit1 crit2]
  (opti-crit/direct-eval #::opti{:order [#::opti{:crit-comp-name :smaller :crit-name :b}
                                         #::opti{:crit-comp-name :smaller :crit-name :a}
                                         #::opti{:crit-comp-name :smaller :crit-name :c}]
                          :crit-comp-name :hierarchise}
                         crit1
                         crit2))

[(hierarchise-test {:a 13 :b 2 :c 100} {:a 13 :b 1 :c 100})
 (hierarchise-test {:a 13 :b 2 :c 100} {:a 13 :b 2 :c 100})
 (hierarchise-test {:a 13 :b 2 :c 100} {:a 13 :b 3 :c 103})]
;; ==> [:worst :equal :better]
#+end_src

#+RESULTS:
: [:worst :equal :better]

The =:order= explains the order to use to examine criteria. Each =:order='s element specify:
   - A =crit-name= defining what key to compare, 
   - The =crit-comp-name= to tell what comparison method to use
   - and the rest of the map used to specify parameters as required by =crit-comp-name=.

The result is =nil= if:
- The =crit-comp-name= is missing or not existing in the registry,
- and this criteria is required to compare two value (meaning all previous values in the order were ties) the whole result is =nil=.
** weighted-sum
A weighted sum of a criteria map multiplies the values of the criteria by weights. Then the smaller weight is better. This is typically used when the criteria is a cost, a time, and that we can translate all values into the criteria.
#+begin_src clojure
(require '[auto-opti.crit-comp :as opti-crit]
          '[auto-opti :as-alias opti])

(def crit-fn
  (opti-crit/crit-comp-fn #::opti{:crit-comp-name :weighted-sum
                           :weights {:a 10 :b 20}}))

[(crit-fn {:a 0 :b 1}{:a 0 :b 1})
 (crit-fn {:a 0 :b 1}{:a 10 :b 1})
 (crit-fn {:a 0 :b 1}{:a -10 :b 1})]
;=> [:equal :better :worst]
#+end_src

#+RESULTS:
: [:equal :better :worst]

The weighted sum is mainly defined with the =:weight= attribute which associates a weight to each criterion. When weight are ={:a 10 :b 20}=, it means that ={:a 1 :b 3}= is evaluated to =10*1+20*3\=70=.

Note that:
- If you'd like the higher weighted sum to be better, simply change weights by their opposite: (={:a 10 :b 20}= is replaced with ={:a -10 :b -20}=).
- Missing weights are defaulted to `0`.

** Strict
A criteria is strictly better (i.e. returns =:better=) than another if it is better on all its values. This is particularly useful in multi objectives to remove dominated solutions.
#+begin_src clojure
(require '[auto-opti.crit-comp :as opti-crit]
         '[auto-opti :as-alias opti])

(opti-crit/direct-eval #::opti{:crit-comp-name :strict
                               :crit-names [:b :a]}
                       {:a 15
                        :b 15
                        :c 25}
                       {:a 14
                        :b 16
                        :c 25})
;; ==> :crit-nc
#+end_src

#+RESULTS:
: :crit-nc

In other words, a strict comparison is close to a hierarchical one, excepts:
- the order of the criteria is not important
- all values are compared, and the comparison returns =:crit-nc= unless all values of a criteria are better
* Advanced
** Build your own registry
The registry implements a wide variety of situations already but you may want to add a new comparison. For this you need to implement:
#+begin_src clojure
(require '[auto-opti.crit-comp :as opti-comp]
         '[auto-opti :as-alias opti])

(def my-registry
  (-> opti-comp/default-registry
      (assoc :bigger2
             {:doc "A naive implementation"
              :params-schema :nil
              :f (fn [_]
                   ;; Potential parameter preparation and precalculations should be done here.
                   (fn [crit1 crit2]
                     (cond
                       (> crit1 crit2) :better
                       (= crit1 crit2) :equal
                       :else :worst)))})))

(opti-crit/direct-eval #::opti{:crit-comp-name :bigger2
                               :registry my-registry
                               :crit-names [:b :a]}
                       10 12)
;; ==> :worst
#+end_src

#+RESULTS:
: :worst

Note the use of your own registry with the =:registry= parameter, note also that the default registry is available and could be overridden or enriched with some new comparisons.

Don't forget:
- Time optimization: your implementation should be time effecient, as comparisons are called so often
- Think about compilation time: the returned function should precompute elements as much as possible. 

** Direct-eval
The =direct-eval= function is mainly intended for demonstration and testing, it is using a crit-comp parameter map to compar both criteria.

Note that this is inefficient when the criteria is used multiple times, which is most often the case in optimisation.
