#+title: Design Decisions

* Decision 0 - Optimization DSL
Optimization has specific needs over mathematical calculations, prng, and so on. So we sugget to create its own set of features, ready to be assembled in a low level DSL.
** Decision
All specific need of optimization are gathered in an optimization library.
** Rationale
Even if there are always some time to save with some more specific technologies, we believe at Hephaistox that flexibility is much more important.

Specific solutions of some parts could always be done later on, but these optimizations are most of the time useless and being able to tweak optimization methods, simulation models is more important than optimizing time.

The cost of flexibility is leveraged by higher workload, but it is mitigated by an higher ability to fine tune parameters, to rewrite the model and do some optimization or write some distributed optimizations.
** Consequence
This library is written to gather these features, all meant to be ready to work together.
* Decision 1 - Optimization flexibilty
** Decision
Make the optimization chain flexible
** Rationale
- Changing a model, its optimization method, its parameters, its evalution criteria, all of that is what is searched for in the design process. This is mainly what is critical to sell.
- Parameter maps are an open mechanism and every data can be enriched 
- Precalculation can turn that parameters into a compiled version of the algorithm.
- Registries are defaulted with standard and simple behaviors, every user can enrich the registry for its own needs.
- Formal checks could be done on the parameters to check user
- That parameters are easy to turn into ML or UI.
** Consequence
Optimization chain is mainly setup with parameter maps and registries.
