#+title: Eval

Evaluates a representation to calculate the associated solution. In =auto-opti= schema, it is where the model is mainly implemented as it describes how to calculate one solution.

The =eval= namespace returns a registry that should be enriched by the user.

* Quick start
#+begin_src clojure
(require '[auto-opti.eval :as opti-eval])

(let [{:keys [valid-pars eval]} (:montecarlo-pi opti-eval/registry)]
  [(if (nil? (valid-pars {}
                         nil
                         {:radius 2 :iterations 100}))
     :pars-valid :pars-invalid)
   (eval {}
         nil
         {:radius 2 :iterations 10000}
         {:seed #uuid "f045161f-7486-4c7d-825d-f3d148996069"})])
;; => [:pars-valid 3.1408859114088594]
#+end_src

#+RESULTS:
: [:pars-valid 3.1408859114088594]

This example evaluates PI with the simple montecarlo method. In that situation the seed is found in the representation.

* Usage
Check the [[file:~/Dev/hephaistox/auto_opti/src/cljc/auto_opti/eval/montecarlo.cljc][montecarlo pi evaluation]] to read a full example.

The description of an evaluation requires two functions:
#+begin_src clojure
(defn eval
   [_params
   iterator-fn
   {:keys [radius iterations]
    :as _model}
   {:keys [seed]
    :as _rep}]
  ;; ...
 ))

(defn valid-pars
  [_params _iterator-fn model]
  ;; ...
  ))
#+end_src

Note that:
- =params= contains useful parameters for the evaluation. =auto-opti= has no constraint on it.
- When =iterator-fn= is a function it is called at each iteration. Useful for rendering and UI.
- =model= is a map describing the model to solve. Contrary to =params= the model is expected to be managed by the optimizer, the one building the problem to solve. 
- =rep= is the description of the solution that will be evaluated. Contrary to model, the data in =rep= are not known in advance and are what the optimization are looking for. Consequently optimization algorithm will search =rep=.

