#+title: Prng
A [[https://en.wikipedia.org/wiki/Pseudorandom_number_generator][pseudo random number generator]] (i.e. =PRNG=) is a tool for modeling randomness in electronic computers. In practice, it’s a mathematical sequence generator that produces numbers that look random.

=auto-opti= library is aiming this generator for discrete optimization, and its specific needs:

- Reproductibility: the same sequence of generated numbers can be produced consistently
- Uniform generation of value pairs
- Produces identical sequences across all supported execution environments (java vs javascript).

* Why a new PRNG library
Properly modelling randomness is a challenging problem — one that dates back to the early days of computer science in 1946 — and periodic breakthroughs (e.g., in 2006) still reshape the field. As a result:

- no single PRNG is universally superior,
- new, more efficient PRNGs may emerge,
- the PRNGs built into programming languages (Java, JavaScript, …) are rarely best-in-class,
- truly cross-platform PRNGs are uncommon (32- vs 64-bit architectures, frontend vs backend), and built-in PRNGs are generally not cross-platform.

The auto-opti library addresses these issues by introducing a parameter map with default PRNG implementations, effectively decoupling the choice of PRNG from its usage.

It provides:

- a clean separation between PRNG implementation and use,
- making it straightforward to switch from one prng to another
- PRNGs that do not depend on platform-specific numeric representations,
- a PRNG that produces identical sequences across all supported execution environments.
* Quick start  
The PRNG creation starts simply with a parameter map, that has default values and could be empty:

#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
   (-> {}
       opti-prng/prng))

(and (= 56
        (opti-prng/as-int prng* 10 100))
     (= 59
        (opti-prng/as-int prng* 10 100))
     (= 89
        (opti-prng/as-int prng* 10 100)))
#+end_src

#+RESULTS:
: true
* Different Prng usages
** Simple usage
When a prng is created, it can be used to generate a random value. Two main implementations are made: one returning integer, the other returning a double. Both implementation returns a value in a range given as parameters of the function call. It is the responsability of the prng implementation to ensure that all values are equiprobable :

#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
  (-> {}
      opti-prng/prng))

(vector (opti-prng/as-int prng* 10 100)
        (opti-prng/as-double prng* 10.0 100.0))
#+end_src

#+RESULTS:
: [56 62.28426460501133]

** Pair of values
For some prng implementation, returning a pair of values need a specific implementation to ensure all pairs have a uniform probability. The =as-int-pair= and =as-double-pair= functions are dealing with this end.

#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
  (-> {}
      opti-prng/prng))

(vector (opti-prng/as-int-pair prng* 10 100)
        (opti-prng/as-double-pair prng* 10.0 100.0))
#+end_src

#+RESULTS:
: [[56 59] [89.0 74.0]]

** A set of random values
The =as-ints= and =as-doubles= functions are helpers to return more than one value. Note that, contrarely to the previous =-pair= implementation, there is no effort made to ensure equiprobability.

#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
  (-> {}
      opti-prng/prng))

(vector (opti-prng/as-ints prng* 3 10 100)
        (opti-prng/as-doubles prng* 3 10.0 100.0))
#+end_src

#+RESULTS:
: [(56 59 89) (44.32935272914683 47.020137246995276 99.99216829772887)]

* Manipulating the seed
When a prng is created, it starts with a seed. 

The =prng= is a statefull object that returns a new random value with each =as-*= call. To repeat the pseudo random sequence, =opti-prng= offers many options:
** Reuse the same seed
#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
  (-> #::opti-prng{:seed #uuid "54b9758a-906f-4ec9-b1eb-1efef7f67e3b"}
      opti-prng/prng))

(def prng2*
  (-> #::opti-prng{:seed #uuid "54b9758a-906f-4ec9-b1eb-1efef7f67e3b"}
      opti-prng/prng))

(vector (opti-prng/as-int prng* 10 100)
        (opti-prng/as-double prng* 10.0 100.0)
        (opti-prng/as-int prng2* 10 100)
        (opti-prng/as-double prng2* 10.0 100.0))
#+end_src

#+RESULTS:
: [56 62.28426460501133 56 62.28426460501133]
** =duplicate=
A prng that is used with duplicate is starting again from the same seed and returns the same pseudo random number sequence.
#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
  (-> #::opti-prng{:seed #uuid "54b9758a-906f-4ec9-b1eb-1efef7f67e3b"}
      opti-prng/prng))

(def tmp
  (vector (opti-prng/as-int prng* 10 100)
          (opti-prng/as-double prng* 10.0 100.0)))

(def prng2*
  (opti-prng/duplicate prng* ))

(vector tmp
        (vector
         (opti-prng/as-int prng2* 10 100)
         (opti-prng/as-double prng2* 10.0 100.0)))
#+end_src

#+RESULTS:
: [[56 62.28426460501133] [56 62.28426460501133]]
** =uuid-seed=
With =uuid-seed= you can extract a prng seed and start again the pseudo random number sequence.
#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
  (-> #::opti-prng{:prng-name :xoroshiro128
                   :seed #uuid "54b9758a-906f-4ec9-b1eb-1efef7f67e3b"}
      opti-prng/prng))

(def tmp
  (vector (opti-prng/as-int prng* 10 100)
          (opti-prng/as-double prng* 10.0 100.0)))

(def prng2*
  (-> #::opti-prng{:prng-name :xoroshiro128
                   :seed (opti-prng/uuid-seed prng*)}
      opti-prng/prng))

(vector tmp
        (vector
         (opti-prng/as-int prng2* 10 100)
         (opti-prng/as-double prng2* 10.0 100.0)))
#+end_src

#+RESULTS:
: [[56 62.28426460501133] [56 62.28426460501133]]

** =reset= 
The =reset= function returns the PRNG to the initial state it had when created, producing the same pseudo-random sequence.
#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
  (-> #::opti-prng{:prng-name :xoroshiro128
                   :seed #uuid "54b9758a-906f-4ec9-b1eb-1efef7f67e3b"}
      opti-prng/prng))

(def tmp
  (vector (opti-prng/as-int prng* 10 100)
          (opti-prng/as-double prng* 10.0 100.0)))

(def prng2*
  (opti-prng/reset prng*))

(vector tmp
        (vector
         (opti-prng/as-int prng2* 10 100)
         (opti-prng/as-double prng2* 10.0 100.0)))
#+end_src

#+RESULTS:
: [[56 62.28426460501133] [56 62.28426460501133]]
* Switching a prng
All previous examples were using the default prng implementation which is xoroshiro128. Turning into a different implementation is simply done with the =::opti-prng/prng-name= parameter that can take one of the registry's value:
#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
  (-> #::opti-prng{:prng-name :built-in
                   :seed #uuid "54b9758a-906f-4ec9-b1eb-1efef7f67e3b"}
      opti-prng/prng))

(vector (opti-prng/as-int prng* 10 100)
        (opti-prng/as-double prng* 10.0 100.0))
#+end_src

#+RESULTS:
: [10.020865747422322 10.351964840676771]

PS: Note that the built-in implementation has no clean seed management, so results will be different for each execution.

* Best practise
For robust randomness, the =auto-opti='s usage best practises are suppose to specify both name and seed :

#+begin_src clojure
(require '[auto-opti.prng :as opti-prng]) 

(def prng*
  (-> #::opti-prng{:prng-name :xoroshiro128
                   :seed #uuid "54b9758a-906f-4ec9-b1eb-1efef7f67e3b"}
      opti-prng/prng))

(vector (opti-prng/as-int prng* 10 100)
        (opti-prng/as-double prng* 10.0 100.0))
#+end_src

#+RESULTS:
: [56 62.28426460501133]

* Advanced setup
** Create your own prng 
You can add some new prngs in the existing registry and then leverage the library's features.

For this, you need to create your generator first, it should implement the =auto-opti.prng/stateful/PRNG='s interface. Then, you should include your prng to the regirstry and use it.

#+begin_src clojure
(require '[auto-opti.prng :as opti-prng])

(defrecord My-PRNG []
  opt-prng-stateful/PRNG
  (duplicate [_] (throw (ex-info "Not implemented." {})))
  (jump [_] (repeatedly 100 rand))
  (reset [_]
    (throw
     (ex-info
      "Not implemented. Leverage another prng or implement https://github.com/trystan/random-seed"
      {})))
  (uuid-seed [_] nil)
  (rnd-int [_ a b] (+ a (mod (rand) (- b a))))
  (rnd-double [_ a b] (+ a (mod (rand) (- b a)))))

(def my-registry
  (-> opti-prng/prng-registry
      (assoc :my-generator (fn [_] (->My-PRNG)))))

 (def prng
   (-> #::opti-prng{:prng-name :my-generator
                    :registry my-registry
                    :seed "54b9758a-906f-4ec9-b1eb-1efef7f67e3b" }
        opti-prng/prng))
  prng
#+end_src

#+RESULTS:
: #auto_opti.prng.impl.built_in.My-PRNG{}
** Jump
With =jump=, one can improve values statistical independance like the prng state is a complete different seed. Most best in class prng implementation offer a proper way to do this effeciently. And it's prng implementer's concern to do it.
When you don't use jump, you may:
- Either get the next value, and we know that two consecutive values may have some biases.
- Either start with a completetly different seed, that impose to store many seeds.

With jump function, you continue with the initial seed but increase statistical independence with previous.

