#+title: Distribution

Generate distribution law.

* Quick start
The distribution law creation is as simple as creating a parameter map and call =distribution=.
#+begin_src clojure
(require '[auto-opti.distribution :as opti-dst])

(def d
  (->  {}
       opti-dst/distribution))

(repeatedly 3 (fn [] (opti-dst/draw d)))
;; => (5.572461274045274E7 1.2475511470520306E9 2.1237962997905297E9)
#+end_src

#+RESULTS:
: (5.572461274045274E7 1.2475511470520306E9 2.1237962997905297E9)

This returns a default result returning a uniform distrubtion law, based on a =xoroshiro128= prng, the seed =#uuid "55008b82-85ca-4439-a629-89e227b4a565"=. The uniform distribution is in =[0;2.147483647E9]=.

* Why another distribution law
First to leverage the PRNG we built. And also to obey the [[file:design_decisions.org][decision 0]].

* Usage
** Comprehensive example
The same example than the quick start, but with no default values used.
#+begin_src clojure
(require '[auto-opti.distribution :as opti-dst]
         '[auto-opti.maths        :as opt-maths])

(def d
  (->  {:prng-name :xoroshiro128
        :dstb-name :uniform
        :a 0
        :b opt-maths/interop-max-integer
        :seed  #uuid "55008b82-85ca-4439-a629-89e227b4a565"}
       opti-dst/distribution))

(repeatedly 3 (fn [] (opti-dst/draw d)))
;; => (5.572461274045274E7 1.2475511470520306E9 2.1237962997905297E9)
#+end_src

#+RESULTS:
: (5.572461274045274E7 1.2475511470520306E9 2.1237962997905297E9)

This returns exactly the same results of course. But now you have control on values.
** Use a specific prng
It is possible to leverage a PRNG created in another context with the =:prng= parameter. This is especially useful if you have more than one distribution in your model, so you share your seed across different needs.

#+begin_src clojure
(require '[auto-opti.distribution :as opti-dst]
         '[auto-opti.prng         :as opti-prng]
         '[auto-opti.maths        :as opt-maths])

(def prng
  (-> {:prng-name :xoroshiro128
       :seed  #uuid "55008b82-85ca-4439-a629-89e227b4a565"}
      opti-prng/prng))

(def d
  (->  {:prng prng
        :dstb-name :uniform
        :a 0
        :b opt-maths/interop-max-integer}
       opti-dst/distribution))

(repeatedly 3 (fn [] (opti-dst/draw d)))
;; => (5.572461274045274E7 1.2475511470520306E9 2.1237962997905297E9)
#+end_src

#+RESULTS:
: (5.572461274045274E7 1.2475511470520306E9 2.1237962997905297E9)

Note that:
- the results are exactly the same than the previous use cases. That said, creating a new distribution will continue to use the same prng and then return a different randomness.
- the =:prng= parameter is higher priority and is used if provided.
** Characteristics
Simple characteristics of distribution are available:
#+begin_src clojure
(require '[auto-opti.distribution :as opti-dst])

(def prng
  (-> {:prng-name :xoroshiro128
       :seed  #uuid "55008b82-85ca-4439-a629-89e227b4a565"}
      opti-prng/prng))

(def d
  (->  {:prng prng
        :dstb-name :uniform
        :a 0
        :b opt-maths/interop-max-integer}
       opti-dst/distribution))

[(opti-dst/draw d)
 (opti-dst/draws d 3)
 (opti-dst/minimum d)
 (opti-dst/maximum d)
 (opti-dst/quantile d 0.2)
 (opti-dst/median d)
 (opti-dst/cumulative d 0.3)]
;; => [55724612.74045274 (1247551147.0520306 2123796299.7905297 819130262.199307) 0 2147483647.0 429496729.40000004 1073741823.5 1.396983862573739e-10]
#+end_src

#+RESULTS:
: [55724612.74045274 (1247551147.0520306 2123796299.7905297 819130262.199307) 0 2147483647.0 429496729.40000004 1073741823.5 1.396983862573739e-10]
** Resolve
Resolving is useful to turn a map describing a distribution law into an actual value.

#+begin_src clojure
(require '[auto-opti.distribution :as opti-dst])

(def prng
  (-> {:prng-name :xoroshiro128
       :seed  #uuid "55008b82-85ca-4439-a629-89e227b4a565"}
      opti-prng/prng))

(def d
  (->  {:prng prng
        :dstb-name :uniform
        :a 0
        :b opt-maths/interop-max-integer}
       opti-dst/distribution))

[(opti-dst/resolve d)
 (opti-dst/resolve 2.3)]
;; => : [55724612.74045274 2.3]
#+end_src

#+RESULTS:
: [55724612.74045274 2.3]
* Advanced
- [[https://en.wikipedia.org/wiki/List_of_probability_distributions][Main distributions]]
- [[https://en.wikipedia.org/wiki/Normal_distribution][normal distribution]]
- [[https://en.wikipedia.org/wiki/Discrete_uniform_distribution][discrete uniform distribution]]
- [[https://en.wikipedia.org/wiki/Poisson_binomial_distribution][Poisson binomial distribution]]
- [[https://en.wikipedia.org/wiki/Noncentral_chi-squared_distribution][noncentral chi-squared distribution]]
